/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import DAO.StudentDao;
import DATABASE.DB_Connection;
import Model.Department;
import Model.Student;
import daoImpl.StudentDaoImpl;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author IBM
 */
public class registrationFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(registrationFrame.class.getName());

    /**
     * Creates new form registrationFrame
     */
    public registrationFrame() {
        initComponents();
        loadDepartments();
    }
     private void loadDepartments() {
        deptBox.addItem("Select Department"); // Default instruction item

        try {
            Connection con = DB_Connection.getDbConnection();
            String query = "SELECT dept_name FROM departments";
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                deptBox.addItem(rs.getString("dept_name"));
            }

            rs.close();
            pst.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        rollNumberLabel = new javax.swing.JLabel();
        departmentLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        rollNumberField = new javax.swing.JTextField();
        deptBox = new javax.swing.JComboBox<>();
        addButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameLabel.setText("Name");

        rollNumberLabel.setText("Roll Number");

        departmentLabel.setText("Department");

        nameField.setText(" ");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rollNumberLabel)
                            .addComponent(departmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameField)
                            .addComponent(rollNumberField)
                            .addComponent(deptBox, 0, 190, Short.MAX_VALUE))))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rollNumberLabel)
                    .addComponent(rollNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departmentLabel)
                    .addComponent(deptBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addComponent(addButton)
                .addContainerGap(269, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        
        System.out.println("Clicked Button");
String name = nameField.getText();
String rollNumber = rollNumberField.getText();
String selectedDept = deptBox.getSelectedItem().toString().trim();

// Step 1: Validate department selection
if (selectedDept.equals("Select Department")) {
    JOptionPane.showMessageDialog(this, "Please select a department.");
    return;
}
int deptId = 0;
 String deptCode = "";
System.out.println("Selected department: [" + selectedDept + "]");
// Step 2: Get dept_id from DB
try {
    Connection con = DB_Connection.getDbConnection();
    String sql = "SELECT dept_id FROM departments WHERE dept_name = ?";
    PreparedStatement pst = con.prepareStatement(sql);
    pst.setString(1, selectedDept);
    ResultSet rs = pst.executeQuery();

    if (rs.next()) {
        deptId = rs.getInt("dept_id");
    }

    rs.close();
    pst.close();
    con.close();
} catch (Exception e) {
    e.printStackTrace();
}

if (deptId == 0) {
    JOptionPane.showMessageDialog(this, "Selected department not found in database.");
    return;
}

// ✅ Construct Department object
Department department = new Department();
department.setDeptId(deptId);
department.setDeptName(selectedDept);
department.setDeptCode(deptCode);

// ✅ Now create and set Student
Student student = new Student();
student.setName(nameField.getText());
student.setRollNumber(rollNumberField.getText());
student.setDepartment(department);
StudentDao studentDao = new StudentDaoImpl();
studentDao.addStudent(student);

//        System.out.println("Clicked Button");
//        String name = nameField.getText();
//        String rollNumber = rollNumberField.getText();
//        String dept = deptBox.getSelectedItem().toString();
//        
//        Student student = new Student();
//         student.setName(name);
//         student.setRollNumber(rollNumber);
//         
//         StudentDao studentDao = new StudentDaoImpl();
//         studentDao.addStudent(student);
//          
    }//GEN-LAST:event_addButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new registrationFrame().setVisible(true));
        
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel departmentLabel;
    private javax.swing.JComboBox<String> deptBox;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField rollNumberField;
    private javax.swing.JLabel rollNumberLabel;
    // End of variables declaration//GEN-END:variables
}
